//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagement.StudentManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subject
    {      
        public Subject()
        {
            this.Students = new HashSet<Student>();
        }
    
        public string Subject_ID { get; set; }
        public string Subject_Name { get; set; }
    
        public virtual ICollection<Student> Students { get; set; }
    }
}
